apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-demo
spec:
  args:
  - name: api-url
    value: http://34.111.87.47/
  metrics:
  - name: webmetric
    successCondition: result == 'true'
    provider:
      web:
        url: "{{ args.api-url }}"
        jsonPath: "{$.results.ok}"