apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-demo
spec:
  metrics:
  - name: webmetric
    successCondition: result == 'true'
    provider:
      web:
        url: "{{ args.api-url }}"
        jsonPath: "{$.results.ok}"